# -*- coding: utf-8 -*-
"""Proyecto Final APP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KssTzoQUhHUJmNewXZs_-pyteVUxvEDq
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

st.title("Predicción del costo de actividades")


df = pd.read_excel("/content/Registro programacion ap.xlsx")

df['Fecha (dd/mm/aa)'] = pd.to_datetime(df['Fecha (dd/mm/aa)'], errors='coerce', dayfirst=True)

st.subheader("Datos originales")
st.dataframe(df)

cols_necesarias = ["Presupuesto", "Tiempo invertido", "Tipo", "Momento", "No. de personas", "Costo"]
df = df.dropna(subset=cols_necesarias)

st.subheader("Datos después de eliminar filas vacías")
st.dataframe(df)

X = df[["Presupuesto", "Tiempo invertido", "Tipo", "Momento", "No. de personas"]]
y = df["Costo"]


categorical_cols = ["Tipo", "Momento"]
numeric_cols = ["Presupuesto", "Tiempo invertido", "No. de personas"]

preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
    ("num", "passthrough", numeric_cols)
])

model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

model.fit(X, y)

st.success("Modelo entrenado correctamente.")

st.subheader("Ingresa los datos para predecir el costo")


pres = st.number_input("Presupuesto", min_value=0.0, step=1.0)
tiempo = st.number_input("Tiempo invertido (minutos)", min_value=0.0, step=1.0)
tipo = st.selectbox("Tipo de actividad", df["Tipo"].unique())
momento = st.selectbox("Momento", df["Momento"].unique())
personas = st.number_input("Número de personas", min_value=1, step=1)


if st.button("Predecir"):
    entrada = pd.DataFrame({
        "Presupuesto": [pres],
        "Tiempo invertido": [tiempo],
        "Tipo": [tipo],
        "Momento": [momento],
        "No. de personas": [personas]
    })

    prediccion = model.predict(entrada)[0]

    st.metric("Costo estimado", f"${prediccion:,.2f}")